modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="minecraft_add"
version="1.9.0"
displayName="Minecraft Add"
displayURL="https://afdian.com/a/newmyshuaibi"
logoFile="logo.png"
credits="myshuaibi"
authors="myshuaibi"
description="English:\\nThis mod adds more interesting items to Minecraft\\n\u7B80\u4F53\u4E2D\u6587\uFF1A\\n\u8FD9\u4E2A\u6A21\u7EC4\u4E3A\u6211\u7684\u4E16\u754C\u6DFB\u52A0\u4E86\u66F4\u591A\u6709\u8DA3\u7684\u7269\u54C1"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minecraft_add]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration